title: Tim Wolock
description: Quantitative researcher in Seattle
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png
